version: "3"
services:

  coli-conc-website:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ./data/_site:/usr/src/app/_site
    environment:
      # URL for site: https://example.com/site/
      - URL=https://example.com
      - PATHPREFIX=site
    restart: unless-stopped
